name: CI/CD Pipeline AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Setting the environment variable for the entire job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t veyg/albiondiscordbot .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push veyg/albiondiscordbot

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: BOT_TOKEN  # Passing the environment variable to the SSH session
          script: |
            # Stop and remove all containers using the veyg/albiondiscordbot image
            docker ps -a | awk '{ print $1,$2 }' | grep veyg/albiondiscordbot | awk '{print $1 }' | xargs -I {} docker stop {}
            docker ps -a | awk '{ print $1,$2 }' | grep veyg/albiondiscordbot | awk '{print $1 }' | xargs -I {} docker rm {}

            # Pull the latest image and run it
            sudo docker pull veyg/albiondiscordbot
            sudo docker run -d -v /ebs-data:/app/data -e BOT_TOKEN=$BOT_TOKEN --name albiondiscordbot veyg/albiondiscordbot

            # Clean up unused (dangling) images
            docker rmi $(docker images -f "dangling=true" -q)