name: CI/CD Pipeline AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Setting the environment variable for the entire job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Install dependencies
        run: npm install
      
      - name: Semantic Release and Version Update
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image with new version
        run: |
          VERSION=$(cat VERSION)
          docker build -t veyg/albiondiscordbot:$VERSION .
          docker tag veyg/albiondiscordbot:$VERSION veyg/albiondiscordbot:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub with new version
        run: |
          VERSION=$(cat VERSION)
          docker push veyg/albiondiscordbot:$VERSION
          docker push veyg/albiondiscordbot:latest

      - name: SSH and Deploy to EC2 with new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: BOT_TOKEN
          script: |
            VERSION=$(cat VERSION)
            # Stop and remove all containers using the veyg/albiondiscordbot image
            docker ps -a | awk '{ print $1,$2 }' | grep veyg/albiondiscordbot | awk '{print $1 }' | xargs -I {} docker stop {}
            docker ps -a | awk '{ print $1,$2 }' | grep veyg/albiondiscordbot | awk '{print $1 }' | xargs -I {} docker rm {}

            # Pull the latest image and run it
            sudo docker pull veyg/albiondiscordbot:$VERSION
            sudo docker run -d -v /ebs-data:/app/data -e BOT_TOKEN=$BOT_TOKEN --name albiondiscordbot veyg/albiondiscordbot:$VERSION

            # Clean up unused (dangling) images
            docker rmi $(docker images -f "dangling=true" -q)
